In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/briankimanzi/Downloads/diabetes-2-1 (2) (1).csv')

# Data Understanding

In [4]:
df.sample(10) # generates a random sample data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
173,1,79,60,42,48,43.5,0.678,23,0
303,5,115,98,0,0,52.9,0.209,28,1
452,0,91,68,32,210,39.9,0.381,25,0
157,1,109,56,21,135,25.2,0.833,23,0
471,0,137,70,38,0,33.2,0.170,22,0
224,1,100,66,15,56,23.6,0.666,26,0
242,3,139,54,0,0,25.6,0.402,22,1
3,1,89,66,23,94,28.1,0.167,21,0
177,0,129,110,46,130,67.1,0.319,26,1
602,1,124,74,36,0,27.8,0.100,30,0

In [5]:
df.head(20) # reading first 20 elements

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [6]:
df.tail(20) # reading last 20 elements

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
750,4,136,70,0,0,31.2,1.182,22,1
751,1,121,78,39,74,39.0,0.261,28,0
752,3,108,62,24,0,26.0,0.223,25,0
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
df.dtypes # checking the data types of the data

Pregnancies                    int64
Glucose                        int64
BloodPressure                  int64
SkinThickness                  int64
Insulin                        int64
BMI                          float64
DiabetesPedigreeFunction     float64
Age                            int64
Outcome                        int64
dtype: object

In [8]:
df.info() # print the concise summary of the data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Pregnancies                768 non-null    int64
 1   Glucose                    768 non-null    int64
 2   BloodPressure              768 non-null    int64
 3   SkinThickness              768 non-null    int64
 4   Insulin                    768 non-null    int64
 5   BMI                        768 non-null    float64
 6   DiabetesPedigreeFunction   768 non-null    float64
 7   Age                        768 non-null    int64
 8   Outcome                    768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [9]:
rows, columns = df.shape
print(f"Rows: {rows}, columns: {columns}")

Rows: 768, columns: 9

In [10]:
df.isna().sum() # checking the missing values

Pregnancies                  0
Glucose                      0
BloodPressure                0
SkinThickness                0
Insulin                      0
BMI                          0
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
dtype: int64

In [17]:
df.columns

Index(['Pregnancies ', 'Glucose ', 'BloodPressure ', 'SkinThickness ',
       'Insulin ', 'BMI  ', 'DiabetesPedigreeFunction ', 'Age ', 'Outcome'],
      dtype='object')

In [26]:
df.rename(columns={'DiabetesPedigreeFunction' :'DiabetesPedigreeFunc'}, inplace=True)

In [22]:
# calculating percentage of missing values
def missing_values_percentage(df: pd.DataFrame):
    """Function to check if there are 
    missing data on the dataset"""
    missing_percent = (df.isna().sum() / len(df)) * 100
    missing_df = pd.DataFrame({'Column':df.columns, 'Missing (%)': missing_percent})
    missing_df = missing_df[missing_df['Missing (%)'] > 0].sort_values(by='Missing (%)', ascending=False)

    return missing_df

In [23]:
missing_values_percentage(df)

Empty DataFrame
Columns: [Column, Missing (%)]
Index: []

In [30]:
df.columns = df.columns.str.lower() # changes the columns to lower cases

In [32]:
# checking duplicate on the dataset
df.duplicated

<bound method DataFrame.duplicated of      pregnancies   glucose   bloodpressure   skinthickness   insulin   bmi    \
0               6       148              72              35         0   33.6
1               1        85              66              29         0   26.6
2               8       183              64               0         0   23.3
3               1        89              66              23        94   28.1
4               0       137              40              35       168   43.1
..            ...       ...             ...             ...       ...    ...
763            10       101              76              48       180   32.9
764             2       122              70              27         0   36.8
765             5       121              72              23       112   26.2
766             1       126              60               0         0   30.1
767             1        93              70              31         0   30.4

     diabetespedigreefunction   age   outcome
0                        0.627    50        1
1                        0.351    31        0
2                        0.672    32        1
3                        0.167    21        0
4                        2.288    33        1
..                         ...   ...      ...
763                      0.171    63        0
764                      0.340    27        0
765                      0.245    30        0
766                      0.349    47        1
767                      0.315    23        0

[768 rows x 9 columns]>