# Mental illnesses Prevalence

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
pd.set_option('Display.Max.columns', None)
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('/Users/briankimanzi/Documents/programming Languages/PythonProgramming/JupyterNoteBook/Datasets/Mental-illnesses-prevalence.csv')

In [7]:
data.head(20)

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized
0,Afghanistan,AFG,1990,0.223206,4.996118,4.713314,0.703023,0.127700
1,Afghanistan,AFG,1991,0.222454,4.989290,4.702100,0.702069,0.123256
2,Afghanistan,AFG,1992,0.221751,4.981346,4.683743,0.700792,0.118844
3,Afghanistan,AFG,1993,0.220987,4.976958,4.673549,0.700087,0.115089
4,Afghanistan,AFG,1994,0.220183,4.977782,4.670810,0.699898,0.111815
5,Afghanistan,AFG,1995,0.219409,4.978228,4.668100,0.699768,0.108507
6,Afghanistan,AFG,1996,0.218465,4.981489,4.665759,0.699650,0.105269
7,Afghanistan,AFG,1997,0.217286,4.987593,4.665013,0.699597,0.101531
8,Afghanistan,AFG,1998,0.216074,4.996858,4.668240,0.699765,0.098050
9,Afghanistan,AFG,1999,0.215068,5.004257,4.673557,0.700054,0.095723
10,Afghanistan,AFG,2000,0.214515,5.008448,4.676880,0.700252,0.094876
11,Afghanistan,AFG,2001,0.214315,5.003872,4.675786,0.700129,0.094547
12,Afghanistan,AFG,2002,0.214188,4.994327,4.672062,0.699779,0.094810
13,Afghanistan,AFG,2003,0.214093,4.981722,4.671881,0.699606,0.094983
14,Afghanistan,AFG,2004,0.214061,4.973161,4.672751,0.699501,0.095531
15,Afghanistan,AFG,2005,0.214097,4.965879,4.673633,0.699439,0.095990
16,Afghanistan,AFG,2006,0.214259,4.962840,4.678040,0.699530,0.096875
17,Afghanistan,AFG,2007,0.214598,4.959720,4.682732,0.699520,0.098696
18,Afghanistan,AFG,2008,0.215027,4.953167,4.688263,0.699480,0.100904
19,Afghanistan,AFG,2009,0.215455,4.949215,4.695408,0.699488,0.103032

In [8]:
data.sample(20)

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized
359,Asia (IHME GBD),NaN,2019,0.293031,3.196159,3.258719,0.336510,0.138726
4508,Paraguay,PRY,1998,0.273869,3.508441,6.145854,1.090560,0.191542
3690,Micronesia (country),FSM,1990,0.269746,3.017696,3.935191,0.264592,0.076112
3487,Maldives,MDV,1997,0.297231,3.473876,3.633668,0.340645,0.097988
5582,Taiwan,TWN,1992,0.295798,2.470251,3.800256,0.193926,0.127588
4111,Niger,NER,1991,0.208085,4.150749,2.812698,0.542865,0.078005
2625,Iceland,ISL,2005,0.276889,2.977520,5.095052,0.905907,0.417604
5472,Suriname,SUR,2002,0.270568,4.670139,4.076613,0.895975,0.191469
1073,Canada,CAN,2013,0.288450,3.215620,4.324433,0.805393,0.424409
1809,Equatorial Guinea,GNQ,1999,0.213266,5.896633,3.862344,0.553341,0.118656
4700,Qatar,QAT,2010,0.285183,3.962330,4.205700,0.745937,0.335636
2599,Hungary,HUN,2009,0.289892,2.879501,3.463751,0.537901,0.169550
2792,Israel,ISR,1992,0.301885,4.542407,3.707592,1.049768,0.304281
6229,Vanuatu,VUT,2009,0.271663,2.989590,3.963931,0.266526,0.074567
57,Africa (IHME GBD),NaN,2017,0.220823,4.453067,3.705067,0.602414,0.122223
5532,Switzerland,CHE,2002,0.279250,3.777192,6.511807,0.937842,0.483703
4293,Norway,NOR,1993,0.282330,3.060759,7.156066,0.835414,0.417540
1662,Dominican Republic,DOM,2002,0.270664,3.968561,4.437084,0.911464,0.188285
2431,Guinea-Bissau,GNB,1991,0.203762,4.362160,3.057194,0.526634,0.086149
4696,Qatar,QAT,2006,0.283613,4.108052,4.283547,0.753427,0.343215