# M-PESA prediction
<img src="Datasets/Images/MPesaFinance.png" alt="Mental Illness Image" width="500" height="450">
<h2> Case study </h2>

<i><h4>Introduction</i></h4>

* M-Pesa is a mobile money service launched by Safaricom, Kenya’s leading telecommunications company, in 2007. It has revolutionized financial transactions, allowing users to send, receive, deposit, and withdraw money using their mobile phones. M-Pesa has played a significant role in financial inclusion, particularly for unbanked populations.

<i><h4>How M-Pesa Works</h4></i>

* M-Pesa enables users to perform transactions via USSD codes or the M-Pesa app. Users register with Safaricom and link their mobile   numbers to an M-Pesa account. Key services include:
- Depositing money at M-Pesa agent shops.
- Sending money to other users and non-users.
- Withdrawing cash from agents or ATMs.
- Paying bills (electricity, water, internet, school fees, etc.).
- Merchant payments through Lipa na M-Pesa.
- Accessing micro-loans and savings via M-Shwari and KCB M-Pesa.
- Overdraft services using Fuliza.<br>

<i><h4>Challenges and Risks</i></h4>

* High transaction costs: Some users find M-Pesa charges expensive for frequent transactions.
* less finance monitoring and alert on overspending money
* Alternative option on cheaper money spending areas

<i><h4>Solution</i></h4>

* Model a system using m-pesa stament to predict your spending
* provide an alternative of a cheaper spending activity
* provide an alert to user when the spending of money is high(email)

In [7]:
import pandas as pd
import numpy as np
import PyPDF2
import pikepdf
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from tabula.io import read_pdf 
from dateutil import parser
from sqlalchemy import create_engine
import mysql.connector

In [4]:
# decrepting the file pdf
input_path = "/Users/briankimanzi/Downloads/Mpesa pdfs/Statement_All_Transactions_20240901_20250301.pdf"
output_path = "/Users/briankimanzi/Downloads/Mpesa pdfs/Tracking.pdf"
password = "102030"

with pikepdf.open(input_path, password=password) as pdf:
    pdf.save(output_path)
path = output_path

In [ ]:
input_path = "/Users/briankimanzi/Downloads/Mpesa pdfs/Statement_All_Transactions_20240901_20250301.pdf"
output_path = "/Users/briankimanzi/Downloads/Mpesa pdfs/Tracking.pdf"
password = "102030"

with pikepdf.open(input_path, password=password) as pdf:
    pdf.save(output_path)
path = output_path

In [5]:
# getting number of pages on the pdf
with open(path, 'rb') as file:
    pdf_reader = PyPDF2.PdfReader(file)
    num_pages = len(pdf_reader.pages)

In [10]:
# extracting data from mpesa pages
def get_data():
    for page_number in range(1, num_pages+1):
        if page_number == 1:
            df =read_pdf(path, pages=page_number)
            data=df[1]
            return_df =data
        else:
            df = read_pdf(path, pages=page_number)
            data=df[0]

        if page_number != 1:
            return_df = pd.concat([return_df, data])

    return return_df.reset_index(drop=True)
working_data = get_data()

In [133]:
working_data

,Receipt No,Completion Time,Details,Transaction Status,Paid in,Withdraw\rn,Balance,Unnamed: 0
0,TC17XS3U67,2025-03-01 15:55:18,Customer Transfer to 254718***450 -\rGideon Ki...,COMPLETED,0.00,80.00,27.00,NaN
1,TC14XHM64C,2025-03-01 14:49:55,M-Shwari Deposit,COMPLETED,0.00,"1,000.00",107.00,NaN
2,TC11XF54B3,2025-03-01 14:34:40,Funds received from 0706***880 - sheila\rmercy...,COMPLETED,"1,100.00",0.00,"1,107.00",NaN
3,TC13WSE6N5,2025-03-01 12:11:53,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,7.00,NaN
4,TBS1THWSOL,2025-02-28 17:50:41,Customer Transfer to 254716***061 -\rNAOMI NYA...,COMPLETED,0.00,10.00,17.00,NaN
5,TBS7SGMUUL,2025-02-28 14:11:19,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,15.00,27.00,NaN
6,TBS8RRTL0E,2025-02-28 11:37:52,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,42.00,NaN
7,TBS6RQCRR2,2025-02-28 11:28:33,Funds received from 254723***863 - JOHN\rKIMANZI,COMPLETED,50.00,0.00,52.00,NaN
8,TBQ1KPEI8L,2025-02-26 19:33:28,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.00,55.00,2.00,NaN
9,TBQ0I2VIHO,2025-02-26 10:07:27,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,50.00,57.00,NaN
10,TBQ8HTR212,2025-02-26 09:03:12,Customer Transfer of Funds Charge,COMPLETED,0.00,13.00,107.00,NaN
11,TBQ8HTR212,2025-02-26 09:03:12,Customer Transfer to 0706***880 - sheila\rmerc...,COMPLETED,0.00,"1,000.00",120.00,NaN
12,TBP7DMJ08Z,2025-02-25 10:12:34,Customer Transfer to 254799***912 -\rMICHAEL M...,COMPLETED,0.00,100.00,"1,120.00",NaN
13,TBP7D1QIGN,2025-02-25 07:27:38,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,"1,220.00",NaN
14,TBP4CWCJ7M,2025-02-25 06:07:00,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,15.00,"1,230.00",NaN
15,TBO4BCSA8A,2025-02-24 18:38:51,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,100.0,"1,245.00",NaN
16,TBO3B3PU6D,2025-02-24 17:53:04,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.00,55.0,"1,345.00",NaN
17,TBO8B37JCG,2025-02-24 17:50:21,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,60.0,"1,400.00",NaN
18,TBO7B2FJJL,2025-02-24 17:46:07,Customer Transfer to 254720***414 -\rNYAGEIKAR...,COMPLETED,0.00,20.0,"1,460.00",NaN
19,TBO99NHCGH,2025-02-24 12:02:15,Merchant Payment to 6627669 - Atomic\rEnterprises,COMPLETED,0.00,70.0,"1,480.00",NaN
20,TBO5928GWN,2025-02-24 09:31:29,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,50.0,"1,550.00",NaN
21,TBO68TYCR6,2025-02-24 08:27:37,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,"1,600.00",NaN
22,TBO68LXN56,2025-02-24 07:13:48,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,15.0,"1,620.00",NaN
23,TBO68HXU8A,2025-02-24 06:08:31,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,"1,635.00",NaN
24,TBN984U269,2025-02-23 22:47:18,Merchant Payment to 6502951 - Ronex\rMogaka On...,COMPLETED,0.00,120.0,"1,655.00",NaN
25,TBN180NJ51,2025-02-23 22:06:57,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,775.00",NaN
26,TBN87ZNTX6,2025-02-23 21:58:27,Funds received from 0799***984 - bridgit\rkavu...,COMPLETED,50.00,0.0,"1,785.00",NaN
27,TBN47N9V5Y,2025-02-23 20:37:56,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,735.00",NaN
28,TBM43FKNRG,2025-02-22 20:33:03,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,745.00",NaN
29,TBM73CMP05,2025-02-22 20:20:34,Merchant Payment to 6502951 - Ronex\rMogaka On...,COMPLETED,0.00,240.0,"1,755.00",NaN
30,TBM33AOS3P,2025-02-22 20:12:33,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,995.00",NaN
31,TBM9ZXDWCT,2025-02-22 12:11:13,Funds received from 254722***289 -\rFELISTUS NGIE,COMPLETED,"2,000.00",0.0,"2,005.00",NaN
32,TBM7Z4W0T7,2025-02-22 08:49:46,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,35.0,5.00,NaN
33,TBL6XR2TBO,2025-02-21 20:05:00,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,40.00,NaN
34,TBK5SWT4TN,2025-02-20 19:12:42,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,50.00,NaN
35,TBK2SUOGGS,2025-02-20 19:03:49,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,70.00,NaN
36,TBK9RFVKZV,2025-02-20 13:48:29,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,80.00,NaN
37,TBJ5OL1I2J,2025-02-19 19:26:18,Merchant Payment to 7385649 - STAR\rBUTCHERY &...,COMPLETED,0.00,50.0,90.00,NaN
38,TBJ6OJVEBM,2025-02-19 19:21:50,Customer Transfer of Funds Charge,COMPLETED,0.00,7.0,140.00,NaN
39,TBJ6OJVEBM,2025-02-19 19:21:50,Customer Payment to Small Business to\r254714*...,COMPLETED,0.00,135.0,147.00,NaN
40,TBJ2O8WKC6,2025-02-19 18:33:39,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,282.00,NaN
41,TBJ7NM7JKB,2025-02-19 16:22:30,Funds received from 254723***863 - JOHN\rKIMANZI,COMPLETED,300.00,0.0,302.00,NaN
42,TBJ1LLXS0N,2025-02-19 07:35:44,Merchant Payment to 7292565 - LINUS\rRONO,COMPLETED,0.00,30.0,2.00,NaN
43,TBJ6LLWBWE,2025-02-19 07:35:16,M-Shwari Withdraw,COMPLETED,30.00,0.0,32.00,NaN
44,TBI7KKYOKT,2025-02-18 20:21:51,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,2.00,NaN
45,TBI5KKS51L,2025-02-18 20:21:11,M-Shwari Withdraw,COMPLETED,11.00,0.0,12.00,NaN
46,TBI2K7SJ26,2025-02-18 19:29:34,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,50.0,1.00,NaN
47,TBI9K7IMW5,2025-02-18 19:28:31,M-Shwari Withdraw,COMPLETED,40.00,0.0,51.00,NaN
48,TBI6H9NCN2,2025-02-18 07:55:40,Merchant Payment to 7886415 -\rMETHUSELAH KIPL...,COMPLETED,0.00,25.00,11.00,NaN
49,TBI6H9LBRQ,2025-02-18 07:55:16,M-Shwari Withdraw,COMPLETED,25.00,0.00,36.00,NaN
50,TBI7H95PAL,2025-02-18 07:51:24,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,40.00,11.00,NaN
51,TBI6H93D2W,2025-02-18 07:50:48,M-Shwari Withdraw,COMPLETED,50.00,0.00,51.00,NaN
52,TBH7DKHKVB,2025-02-17 11:17:55,Customer Payment to Small Business to\r0745***...,COMPLETED,0.00,30.00,1.00,NaN
53,TBH8DKE1W8,2025-02-17 11:17:16,M-Shwari Withdraw,COMPLETED,30.00,0.00,31.00,NaN
54,TBH7CH9YXH,2025-02-17 01:28:44,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,1.00,NaN
55,TBH0CH9M00,2025-02-17 01:28:02,M-Shwari Withdraw,COMPLETED,10.00,0.00,11.00,NaN
56,TBG6BJBOGU,2025-02-16 19:45:26,Merchant Payment to 547648 - Novia\rSolutions,COMPLETED,0.00,"2,000.00",1.00,NaN
57,TBG9BIA7JJ,2025-02-16 19:41:05,M-Shwari Withdraw,COMPLETED,"2,000.00",0.00,"2,001.00",NaN
58,TBG8B9MR40,2025-02-16 19:05:25,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.00,1.00,NaN
59,TBG1AV3AEN,2025-02-16 17:48:34,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.00,21.00,NaN
60,TBG39VM5NN,2025-02-16 13:54:48,Customer Payment to Small Business to\r254714*...,COMPLETED,0.00,50.00,41.00,NaN
61,TBG79TI4EX,2025-02-16 13:40:07,Merchant Payment to 747889 - JUJA\rECOMATT SUP...,COMPLETED,0.00,100.00,91.00,NaN
62,TBG49QU28Y,2025-02-16 13:21:20,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,191.00,NaN
63,TBG19QIQU7,2025-02-16 13:19:04,M-Shwari Withdraw,COMPLETED,200.00,0.00,201.00,NaN
64,TBG79EPO0F,2025-02-16 11:50:30,Pay Bill to 921961 - JKUAT CHRISTIAN\rUNION Ac...,COMPLETED,0.00,50.00,1.00,NaN
65,TBG49EMTNM,2025-02-16 11:49:50,M-Shwari Withdraw,COMPLETED,50.00,0.00,51.00,NaN
66,TBG9981VPP,2025-02-16 10:58:37,Customer Transfer to 254728***739 - JOHN\rMUTHONI,COMPLETED,0.00,50.00,1.00,NaN
67,TBG397XQIP,2025-02-16 10:57:41,M-Shwari Withdraw,COMPLETED,50.00,0.00,51.00,NaN
68,TBG58C32P5,2025-02-16 01:11:16,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,50.00,1.00,NaN
69,TBG58C2INR,2025-02-16 01:10:32,M-Shwari Withdraw,COMPLETED,50.00,0.00,51.00,NaN
70,TBF74OHCYV,2025-02-15 11:04:48,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,50.00,1.00,NaN
71,TBF54NOHQL,2025-02-15 10:59:35,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,51.00,NaN
72,TBE61EM7EI,2025-02-14 16:59:26,Merchant Payment to 7292565 - LINUS\rRONO,COMPLETED,0.00,75.00,61.00,NaN
73,TBE51EIIS1,2025-02-14 16:58:51,M-Shwari Withdraw,COMPLETED,100.00,0.00,136.00,NaN
74,TBE81DP496,2025-02-14 16:54:09,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,36.00,NaN
75,TBD7XN0SUX,2025-02-13 22:50:20,Pay Bill Charge,COMPLETED,0.00,2.00,46.00,NaN
76,TBD7XN0SUX,2025-02-13 22:50:20,Pay Bill to 909090 - KACH AIRTIME\rVENTURES A...,COMPLETED,0.00,5.00,48.00,NaN
77,TBD0XMY3VC,2025-02-13 22:49:28,M-Shwari Withdraw,COMPLETED,50.00,0.00,53.00,NaN
78,TBD1XMPKLF,2025-02-13 22:46:35,Pay Bill Charge,COMPLETED,0.00,2.00,3.00,NaN
79,TBD1XMPKLF,2025-02-13 22:46:35,Pay Bill to 909090 - KACH AIRTIME\rVENTURES A...,COMPLETED,0.00,40.00,5.00,NaN
80,TBD3XMMVI7,2025-02-13 22:45:44,Customer Transfer to 254724***441 -\rJAMES MUN...,COMPLETED,0.00,80.00,45.00,NaN
81,TBD9XJZ6UV,2025-02-13 22:18:29,Customer Payment to Small Business to\r0745***...,COMPLETED,0.00,100.00,125.00,NaN
82,TBD7XJV42X,2025-02-13 22:17:25,M-Shwari Withdraw,COMPLETED,200.00,0.00,225.00,NaN
83,TBD6W92BJI,2025-02-13 18:30:06,Merchant Payment to 6033767 - HOSEA\rKAHURA WA...,COMPLETED,0.00,20.00,25.00,NaN
84,TBD7W8TIB9,2025-02-13 18:28:55,M-Shwari Withdraw,COMPLETED,20.00,0.00,45.00,NaN
85,TBD3W7L64N,2025-02-13 18:22:55,Customer Payment to Small Business to\r0115***...,COMPLETED,0.00,100.00,25.00,NaN
86,TBD6W50IWO,2025-02-13 18:09:49,Customer Transfer to 254791***072 - john\rkiar...,COMPLETED,0.00,100.00,125.00,NaN
87,TBD4W4XQM2,2025-02-13 18:09:25,M-Shwari Withdraw,COMPLETED,200.00,0.00,225.00,NaN
88,TBD3UBHQ4F,2025-02-13 10:53:07,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.00,30.00,25.00,NaN
89,TBD5UB5S1F,2025-02-13 10:50:50,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,145.00,55.00,NaN
90,TBD6UB3X7C,2025-02-13 10:50:24,M-Shwari Withdraw,COMPLETED,200.00,0.00,200.00,NaN
91,TBC5SV3CDN,2025-02-12 21:17:11,Merchant Payment to 7886415 -\rMETHUSELAH KIPL...,COMPLETED,0.00,250.00,0.00,NaN
92,TBC6SUZWPG,2025-02-12 21:16:46,M-Shwari Withdraw,COMPLETED,30.00,0.00,250.00,NaN
93,TBC8SUS0A2,2025-02-12 21:15:21,M-Shwari Withdraw,COMPLETED,190.00,0.00,220.00,NaN
94,TBC3ST79ZF,2025-02-12 21:06:23,Customer Payment to Small Business to\r254714*...,COMPLETED,0.00,60.00,30.00,NaN
95,TBC5SSPI3D,2025-02-12 21:03:40,Merchant Payment to 7507293 - STELLAH\rKEMUNTO...,COMPLETED,0.00,80.00,90.00,NaN
96,TBC3SRXXW5,2025-02-12 20:59:33,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,170.00,NaN
97,TBC5SQHY5F,2025-02-12 20:52:07,Customer Transfer of Funds Charge,COMPLETED,0.00,7.00,180.00,NaN
98,TBC5SQHY5F,2025-02-12 20:52:07,Customer Payment to Small Business to\r0791***...,COMPLETED,0.00,130.00,187.00,NaN
99,TBC8SQCC2I,2025-02-12 20:51:20,M-Shwari Withdraw,COMPLETED,200.00,0.00,317.00,NaN
100,TBC1SOSYU7,2025-02-12 20:43:42,Pay Bill to 247247 - Equity Paybill Account\rA...,COMPLETED,0.00,100.00,117.00,NaN
101,TBC0SO50P8,2025-02-12 20:40:32,Customer Transfer of Funds Charge,COMPLETED,0.00,7.00,217.00,NaN
102,TBC0SO50P8,2025-02-12 20:40:32,Customer Transfer to 254711***423 -\rBERYL AUMA,COMPLETED,0.00,300.00,224.00,NaN
103,TBC7SO1PLX,2025-02-12 20:40:04,M-Shwari Withdraw,COMPLETED,500.00,0.00,524.00,NaN
104,TBC5RX17QL,2025-02-12 18:49:03,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,3.00,24.00,NaN
105,TBC6RSLR2Q,2025-02-12 18:28:25,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,50.00,27.00,NaN
106,TBC5RSFQI1,2025-02-12 18:27:34,M-Shwari Withdraw,COMPLETED,50.00,0.00,77.00,NaN
107,TBC3R8Q6O7,2025-02-12 16:37:48,Merchant Payment to 6862957 - LOISE\rMBUGUA 2,COMPLETED,0.00,70.00,27.00,NaN
108,TBC2QNYLJY,2025-02-12 14:13:52,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,97.00,NaN
109,TBC9QNNXDL,2025-02-12 14:11:49,M-Shwari Withdraw,COMPLETED,100.00,0.00,107.00,NaN
110,TBC3PG39C3,2025-02-12 09:06:39,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,7.00,NaN
111,TBB1NTILJV,2025-02-11 19:45:09,Merchant Payment to 596742 - RUTH\rNJERI MUNGAI 1,COMPLETED,0.00,200.00,17.00,NaN
112,TBB0NTD15O,2025-02-11 19:44:34,M-Shwari Withdraw,COMPLETED,200.00,0.00,217.00,NaN
113,TBB8NSSCDO,2025-02-11 19:42:23,Merchant Payment to 596742 - RUTH\rNJERI MUNGAI 1,COMPLETED,0.00,50.00,17.00,NaN
114,TBB1NRNFF3,2025-02-11 19:38:02,Customer Transfer of Funds Charge,COMPLETED,0.00,7.00,67.00,NaN
115,TBB1NRNFF3,2025-02-11 19:38:02,Customer Transfer to 254713***509 -\rCLARIS ON...,COMPLETED,0.00,200.00,74.00,NaN
116,TBB8NRAIYQ,2025-02-11 19:36:42,M-Shwari Withdraw,COMPLETED,200.00,0.00,274.00,NaN
117,TBB6KI4BFS,2025-02-11 06:27:51,M-Shwari Deposit,COMPLETED,0.00,"4,800.00",74.00,NaN
118,TBB5KHXYCJ,2025-02-11 06:24:26,Business Payment from 547701 - National\rBank ...,COMPLETED,"4,850.00",0.00,"4,874.00",NaN
119,TBA0KB5USQ,2025-02-10 23:37:33,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.00,24.00,NaN
120,TBA1I6640R,2025-02-10 16:13:00,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.00,70.00,34.00,NaN
121,TBA7I5SACT,2025-02-10 16:10:22,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.0,60.0,104.0,NaN
122,TBA4I3E716,2025-02-10 15:53:50,Funds received from 254718***450 -\rGideon Kip...,COMPLETED,50.0,0.0,164.0,NaN
123,TBA5I380IX,2025-02-10 15:52:43,Customer Payment to Small Business to\r0794***...,COMPLETED,0.0,100.0,114.0,NaN
124,TBA8HUJDC2,2025-02-10 14:51:26,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,214.0,NaN
125,TBA0HUDS3Y,2025-02-10 14:50:22,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,229.0,NaN
126,TBA9GXXU57,2025-02-10 11:13:56,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,20.0,239.0,NaN
127,TBA1GL6NDH,2025-02-10 09:46:20,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,259.0,NaN
128,TB96FLGBL2,2025-02-09 22:11:34,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,269.0,NaN
129,TB99F3LZRD,2025-02-09 20:21:50,Customer Transfer of Funds Charge,COMPLETED,0.0,7.0,279.0,NaN
130,TB99F3LZRD,2025-02-09 20:21:50,Customer Transfer to 0759***856 - Mutua\rPatrick,COMPLETED,0.0,150.0,286.0,NaN
131,TB98CWK8Z6,2025-02-09 12:40:12,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,20.0,436.0,NaN
132,TB90CT5WHU,2025-02-09 12:15:24,Funds received from 254722***289 -\rFELISTUS NGIE,COMPLETED,300.0,0.0,456.0,NaN
133,TB92BOX3HE,2025-02-09 04:02:54,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,156.0,NaN
134,TB99BO0DV5,2025-02-09 02:46:47,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,171.0,NaN
135,TB95BMA7V9,2025-02-09 01:08:03,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,186.0,NaN
136,TB89B8WODV,2025-02-08 21:54:21,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,20.0,201.0,NaN
137,TB82B6HTY0,2025-02-08 21:38:55,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,221.0,NaN
138,TB83ARCTGT,2025-02-08 20:22:03,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,231.0,NaN
139,TB8384M6ML,2025-02-08 11:38:08,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,241.0,NaN
140,TB846ZCD5I,2025-02-08 02:20:12,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,251.0,NaN
141,TB806YBT00,2025-02-08 01:17:34,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,15.0,266.0,NaN
142,TB785C7SFQ,2025-02-07 18:26:35,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,20.0,281.0,NaN
143,TB754YQ9Z7,2025-02-07 17:18:08,Customer Transfer to 254791***072 - john\rkiar...,COMPLETED,0.0,50.0,301.0,NaN
144,TB754X898X,2025-02-07 17:09:38,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,351.0,NaN
145,TB734NDJX1,2025-02-07 16:09:56,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,20.0,361.0,NaN
146,TB763RIA0S,2025-02-07 12:41:03,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,381.0,NaN
147,TB68XWF9BS,2025-02-06 11:36:21,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.0,10.0,391.0,NaN
148,TB52VKM4Z0,2025-02-05 19:46:05,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.0,20.0,401.0,NaN
149,TB59VJQ9VX,2025-02-05 19:42:47,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.0,95.0,421.0,NaN
150,TB50VJ7WXS,2025-02-05 19:40:52,Customer Payment to Small Business to\r254722*...,COMPLETED,0.0,40.0,516.0,NaN
151,TB57T6N0OZ,2025-02-05 11:30:04,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.0,50.0,556.0,NaN
152,TB58T5JNUW,2025-02-05 11:22:35,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,10.0,606.00,NaN
153,TB50T5GVCW,2025-02-05 11:22:03,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,30.0,616.00,NaN
154,TB56T4PMTW,2025-02-05 11:16:51,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,646.00,NaN
155,TB45O4IZ45,2025-02-04 09:17:16,Customer Transfer to 254799***912 -\rMICHAEL M...,COMPLETED,0.00,100.0,656.00,NaN
156,TB35N5LPZL,2025-02-03 21:45:58,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,756.00,NaN
157,TB39MO90J5,2025-02-03 20:15:21,Customer Transfer of Funds Charge,COMPLETED,0.00,7.0,766.00,NaN
158,TB39MO90J5,2025-02-03 20:15:21,Customer Payment to Small Business to\r254714*...,COMPLETED,0.00,180.0,773.00,NaN
159,TB28IRH0JM,2025-02-02 22:51:45,Merchant Payment to 6502951 - Ronex\rMogaka On...,COMPLETED,0.00,120.0,953.00,NaN
160,TB23IMQGAB,2025-02-02 22:02:57,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,073.00",NaN
161,TB23IMMGHX,2025-02-02 22:02:00,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,"1,083.00",NaN
162,TB28IC3TBK,2025-02-02 20:52:10,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,50.0,"1,103.00",NaN
163,TB24FB15J8,2025-02-02 09:51:02,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,95.0,"1,153.00",NaN
164,TB23EQ4MKH,2025-02-02 04:01:10,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,50.0,"1,248.00",NaN
165,TB24EPF07I,2025-02-02 03:00:43,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,15.0,"1,298.00",NaN
166,TB13E7XZOF,2025-02-01 21:34:14,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,313.00",NaN
167,TB14D64VMI,2025-02-01 18:46:51,Merchant Payment to 6502951 - Ronex\rMogaka On...,COMPLETED,0.00,170.0,"1,323.00",NaN
168,TB11D5LVEH,2025-02-01 18:44:29,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,"1,493.00",NaN
169,TB16A8C28G,2025-02-01 07:35:17,Funds received from 254722***289 -\rFELISTUS NGIE,COMPLETED,"1,500.00",0.0,"1,503.00",NaN
170,TAV88G1F3A,2025-01-31 18:42:41,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,3.00,NaN
171,TAV48EC5WS,2025-01-31 18:35:05,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,25.0,13.00,NaN
172,TAT1ZZ5FYH,2025-01-29 22:42:20,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,38.00,NaN
173,TAT2Y6EG4I,2025-01-29 16:59:10,Customer Transfer to 254705***586 -\rEUNICE NY...,COMPLETED,0.00,25.0,48.00,NaN
174,TAT7Y5XRLR,2025-01-29 16:56:18,Merchant Payment to 7886415 -\rMETHUSELAH KIPL...,COMPLETED,0.00,50.0,73.00,NaN
175,TAT9WD27BT,2025-01-29 09:14:34,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,20.0,123.00,NaN
176,TAS2V7JPTG,2025-01-28 20:28:34,Pay Bill Online to 4076749 - TINGG Acc.\r25410...,COMPLETED,0.00,10.0,143.00,NaN
177,TAS9SC9Z5Z,2025-01-28 09:42:08,Pay Bill to 888880 - KPLC PREPAID Acc.\r371659...,COMPLETED,0.00,50.0,153.00,NaN
178,TAR9QJR8Q3,2025-01-27 19:10:11,Merchant Payment to 686190 - STEPHEN\rKIARIE,COMPLETED,0.00,15.0,203.00,NaN
179,TAR3QII70J,2025-01-27 19:04:43,Customer Payment to Small Business to\r254714*...,COMPLETED,0.00,60.0,218.00,NaN
180,TAR8QIF5GI,2025-01-27 19:04:21,Customer Transfer of Funds Charge,COMPLETED,0.00,7.0,278.00,NaN

In [138]:
# Reading other dataset
Data1 = pd.read_excel('/Users/briankimanzi/Documents/programming Languages/PythonProgramming/JupyterNoteBook/Datasets/MpesaStatement_Katra.xlsx')
Data2 = pd.read_excel('/Users/briankimanzi/Documents/programming Languages/PythonProgramming/JupyterNoteBook/Datasets/MPESA_Marylyne.xlsx')

In [142]:
Data2.sample(20)

,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance
248,TBK1RZOXVB,2025-02-20 16:09:59.990000,Customer Payment to Small Business to - 2547**...,Completed,NaN,-50,691.78
991,SJF27SGCHC,2024-10-15 18:54:00,Merchant Payment Fuliza M-Pesa to 582667 - JAC...,Completed,NaN,-65,0
824,SKE6QYL3HU,2024-11-14 00:00:00,Merchant Payment to 114121 - WILSON KINYANJUI ...,Completed,NaN,-65,266.67
998,SJF778G0B5,2024-10-15 17:12:59.990000,OverDraft of Credit Party,Completed,160,NaN,160
0,TD349XUJFS,2025-04-03 18:27:59.962000,Merchant Payment to 168364 - SAWA SHOP 4,Completed,NaN,-65,1260.75
295,TBD7W5R59T,2025-02-13 18:13:00.019000,Merchant Payment Fuliza M-Pesa to 9472378 - Mo...,Completed,NaN,-100,0
887,SK1777HBDR,2024-11-01 15:06:59.990000,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-370,28808.54
350,TB47QHFTMD,2025-02-04 18:27:00,Pay Bill Charge,Completed,NaN,-5,5684.7
214,TBP2FHAW6M,2025-02-25 17:44:59.971000,Customer Transfer Fuliza MPesa to - 07******22...,Completed,NaN,-10,0
715,SKR4D47PW8,2024-11-27 20:21:00.029000,Merchant Payment Fuliza M-Pesa to 679315 - JOA...,Completed,NaN,-60,0
320,TB91CN86R5,2025-02-09 11:30:00.029000,Merchant Payment to 6692991 - STEPHEN MUCHERU ...,Completed,NaN,-45,830.7
932,SJQ1HS06W3,2024-10-26 18:20:59.971000,OverDraft of Credit Party,Completed,65,NaN,65
368,TAV79QS0G3,2025-01-31 22:36:59.990000,Funds received from - 07******320 SITEYIA TIAM...,Completed,1500,NaN,1500
1028,SJB0OOX9A0,2024-10-11 11:19:59.981000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-200,0
286,TBE41RQXZC,2025-02-14 18:08:00.038000,Deposit of Funds at Agent Till 453478 - Maryju...,Completed,1000,NaN,1000
618,SL90SMN2ZU,2024-12-09 12:15:59.990000,Customer Payment to Small Business to - 2547**...,Completed,NaN,-100,2362.08
858,SK928HBDPI,2024-11-09 00:00:00,Customer Payment to Small Business to - 2547**...,Completed,NaN,-70,341.56
813,SKF1UCS2FJ,2024-11-15 00:00:00,Customer Send Money to Micro SME Business wit...,Completed,NaN,-30,0
340,TB60ZAFWXK,2025-02-06 17:06:59.962000,Customer Transfer to - 2547******725 WELDON KOECH,Completed,NaN,-1550,3120.7
571,SLG7NI7JOL,2024-12-16 11:35:00.010000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-500,0

<h3><i>Data cleaning </i></h3>

In [49]:
# function to remove the commas on the dataset
def remove_comma(x):
    x = str(x)
    x = x.replace(',', '')
    return x

In [53]:
data = working_data.copy()
data['Paid in'] = data['Paid in'].apply(lambda x: remove_comma(x))
data['Withdraw\rn'] = data['Withdraw\rn'].apply(lambda x : remove_comma(x))
data['Balance'] = data['Balance'].apply(lambda x: remove_comma(x))

In [14]:
# changing data type
data = data.astype({
    'Paid in': float,
    'Withdraw\rn':float,
    'Balance':float
})

In [15]:
# dropping unwanted columns
data.drop(columns=['Unnamed: 0'], inplace=True)

In [16]:
# Anonymising the dataset 
def transaction(x):
    x = str(x).strip()
    if x.startswith('Merchant Payment'):
        index = x.find(' - ')+2
        name = x[index:].strip().upper()
        
        return 'BUY GOODS', name

    elif x.startswith('Deposit of funds'):
        index = x.find(' - ')
        name = x[index:].strip().upper()
        
        return 'AGENT DEPOSIT', name

    elif x.startswith('OD Loan Repayment'):
        return 'FULIZA REPAYMENT', 'FULIZA'

    elif x.startswith('OverDraft of Credit Party'):
        return 'FULIZA TAKEN', 'FULUZA'

    elif x.startswith('M-Shwari Deposit'):
        return 'M-SHWARI DEPOSIT FROM M-PESA', 'M-SHWARI'
        
    elif x.startswith('KCB M-PESA Deposit'):
        return 'KCB M-PESA DEPOSIT FROM M-PESA', 'KCB DEPOSIT'

    elif x.startswith('KCB M-PESA Withdraw'):
        return 'KCB M-PESA WITHDRAW FROM M-PESA', 'KCB WITHDRAW'

    elif x.startswith('Customer Transfer'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
                
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        return 'SEND MONEY', name

    elif x.startswith('M-Shwari Withdraw'):
        
        return 'M-SHWARI WITHDRAW FROM M-PESA', 'M-SHWARI WITHDRAW'

    elif x.startswith('Pay Bill'):
        if x.strip() == 'Pay Bill Charge':
            
            return 'PAY BILL CHARGES', 'TRANSACTION COST'
        else:
            index = x.find(' - ')+2
            end = x.lower().find('acc')
            name = x[index:end].strip().upper()
            
            return 'PAY BILL', name

    elif x.startswith('Funds received'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        
        return 'RECEIVED FUNDS', name

    elif x.startswith('Customer Payment to Small Business') or x.startswith('Customer Send Money'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        
        return 'POCHI LA BIASHARA', name

    elif x.startswith('Airtime Purchase'):
        return 'AIRTIME PURCHASE', 'AIRTIME'

    elif x.startswith('Business Payment From'):
        index = x.find(' - ')
        end = x.lower().find('via')
        to_search = x[index:]
        last = 1
        name = x[index:end].strip().upper()
        return 'FUNDS RECEIVED FROM BUSINESS', name

    elif x.startswith('Customer Transfer of Funds Charge'):
        return 'TRANSACTION COST', 'TRANSACTION COST'
    
    elif x.startswith('Buy Bundles Online'):
        return 'BUNDLES PURCHASE', 'BUNDES PURCHASE'
    
    elif x.startswith('Customer Withdrawal'):
        index = x.find(' - ')
        name = x[index:].strip().upper()
        return 'CASH WITHDRAWAL', name
    
    elif x.startswith('Withdrawal Charge'):
        return 'CASH WITHDRAWAL CHARGES', "TRANSACTION COST"
    
    elif x.startswith('Savings Contribution'):
        return 'TO HUSTLER FUND SAVINGS', 'HUSTLER FUND'
    
    elif x.startswith('Term Loan Disbursement for H- Fund') or x.startswith('Term Loan Disbursement for H-Fund'):
        return 'HUSTLER FUND Disbursement'.upper(), 'HUSTLER FUND'
    
    elif x.startswith('Term Loan Repayment for H- Fund') or x.startswith('Term Loan Repayment for H-Fund'):
        return 'HUSTLER FUND REPAYMENT', 'HUSTLER FUND'
    
    else:
        return 'UNIDENTIFIED', 'UNIDENTIFIED'

In [145]:
data['Details'] = data['Details'].apply(lambda x: x.replace('\r', ' '))

In [18]:
details = list(data['Details'].apply(lambda x: transaction(x)).values)
transactionType = [i[0] for i in details]
TransactionParty = [i[1] for i in details]

In [19]:
# changing the date format
def change_date(date):
    date = parser.parse(date)
    return (date.year, date.month, date.day, date.weekday(),date.hour, date.minute, date.second)

In [20]:
date = data['Completion Time'].apply(lambda x: change_date(x)).values
Year = [i[0] for i in date]
Month = [i[1] for i in date]
Date = [i[2] for i in date]
Weekday = [i[3] for i in date]
Hour = [i[4] for i in date]
Minute = [i[5] for i in date]
Seconds = [i[6] for i in date]

transactionDay = []

reverseDay = Date.copy()[::-1]
datey = reverseDay[0]

d = 1

for i in reverseDay:
    if i == datey:
        transactionDay.append(d)
    else:
        datey = i
        d += 1
        transactionDay.append(d)

transactionDay.reverse()

In [21]:
receipt = list(data['Receipt No'].values)

In [22]:
paid_in = data['Paid in'].fillna('NAN_VALUE').values

In [23]:
def withdrawAmount(x):
    try:
        if x < 0:
            return -x
        else:
            return x
    except:
        return x

In [24]:
withdraw = list(data['Withdraw\rn'].apply(lambda x: withdrawAmount(x)).values)
withdraw

[80.0,
 1000.0,
 0.0,
 10.0,
 10.0,
 15.0,
 10.0,
 0.0,
 55.0,
 50.0,
 13.0,
 1000.0,
 100.0,
 10.0,
 15.0,
 100.0,
 55.0,
 60.0,
 20.0,
 70.0,
 50.0,
 20.0,
 15.0,
 20.0,
 120.0,
 10.0,
 0.0,
 10.0,
 10.0,
 240.0,
 10.0,
 0.0,
 35.0,
 10.0,
 20.0,
 10.0,
 10.0,
 50.0,
 7.0,
 135.0,
 20.0,
 0.0,
 30.0,
 0.0,
 10.0,
 0.0,
 50.0,
 0.0,
 25.0,
 0.0,
 40.0,
 0.0,
 30.0,
 0.0,
 10.0,
 0.0,
 2000.0,
 0.0,
 20.0,
 20.0,
 50.0,
 100.0,
 10.0,
 0.0,
 50.0,
 0.0,
 50.0,
 0.0,
 50.0,
 0.0,
 50.0,
 10.0,
 75.0,
 0.0,
 10.0,
 2.0,
 5.0,
 0.0,
 2.0,
 40.0,
 80.0,
 100.0,
 0.0,
 20.0,
 0.0,
 100.0,
 100.0,
 0.0,
 30.0,
 145.0,
 0.0,
 250.0,
 0.0,
 0.0,
 60.0,
 80.0,
 10.0,
 7.0,
 130.0,
 0.0,
 100.0,
 7.0,
 300.0,
 0.0,
 3.0,
 50.0,
 0.0,
 70.0,
 10.0,
 0.0,
 10.0,
 200.0,
 0.0,
 50.0,
 7.0,
 200.0,
 0.0,
 4800.0,
 0.0,
 10.0,
 70.0,
 60.0,
 0.0,
 100.0,
 15.0,
 10.0,
 20.0,
 10.0,
 10.0,
 7.0,
 150.0,
 20.0,
 0.0,
 15.0,
 15.0,
 15.0,
 20.0,
 10.0,
 10.0,
 10.0,
 15.0,
 15.0,
 20.0,
 50.0,
 10.0,
 20.0,
 10.0,
 10.0,
 20.0,
 95.0,
 40.0,
 50.0,
 10.0,
 30.0,
 10.0,
 100.0,
 10.0,
 7.0,
 180.0,
 120.0,
 10.0,
 20.0,
 50.0,
 95.0,
 50.0,
 15.0,
 10.0,
 170.0,
 10.0,
 0.0,
 10.0,
 25.0,
 10.0,
 25.0,
 50.0,
 20.0,
 10.0,
 50.0,
 15.0,
 60.0,
 7.0,
 125.0,
 10.0,
 0.0,
 30.0,
 100.0,
 30.0,
 10.0,
 30.0,
 5.0,
 300.0,
 50.0,
 10.0,
 80.0,
 30.0,
 10.0,
 20.0,
 95.0,
 10.0,
 90.0,
 20.0,
 115.0,
 2.0,
 20.0,
 90.0,
 1100.0,
 2.0,
 30.0,
 2.0,
 20.0,
 100.0,
 80.0,
 0.0,
 0.0,
 10.0,
 45.0,
 0.0,
 100.0,
 0.0,
 7.0,
 170.0,
 0.0,
 0.0,
 40.0,
 0.0,
 2.0,
 10.0,
 0.0,
 2.0,
 10.0,
 120.0,
 0.0,
 2500.0,
 0.0,
 2.0,
 10.0,
 60.0,
 2.0,
 10.0,
 0.0,
 2.0,
 10.0,
 0.0,
 40.0,
 0.0,
 115.0,
 0.0,
 0.0,
 2.0,
 10.0,
 30.0,
 0.0,
 2.0,
 20.0,
 0.0,
 40.0,
 0.0,
 55.0,
 0.0,
 90.0,
 0.0,
 100.0,
 0.0,
 2.0,
 10.0,
 0.0,
 70.0,
 0.0,
 70.0,
 0.0,
 2.0,
 20.0,
 0.0,
 60.0]

In [25]:
transaction_Data = []

for i in range(len(paid_in)):
    try:
        x = float(paid_in[i])
        transaction_Data.append((x, 'PAID IN'))
    except:
        x = float(withdraw[i])
        transaction_Data.append((x, 'WITHDRAW'))

In [26]:
transaction_amount = [i[0] for i in transaction_Data]
paid_in_or_withdraw = [i[1] for i in transaction_Data]

In [27]:
balance =list(data["Balance"].values)

In [28]:
final_data = pd.DataFrame({
    "Receipt":receipt,
    "transaction_Day": transactionDay,
    "Year" : Year,
    "Month" : Month,
    "Date" : Date,
    "Weekday" : Weekday,
    "Hour" : Hour,
    "Minute" : Minute,
    "Seconds" : Seconds,
    "Transaction_type" : transactionType,
    "Transaction_party" : TransactionParty,
    "Transaction_amount" : transaction_amount,
    "paid_in_or_Withdraw" : paid_in_or_withdraw,
    "Balance" : balance
})
final_data.set_index('Receipt', inplace=True)

In [34]:
# connecting to the database
DB_USER = "root"
DB_PASSWORD = "673gezmigel"
DB_HOST = "localhost"
DB_PORT = "3306"
DB_NAME = "mpesa"

# creating engine
engine = create_engine(f"mysql+mysqlconnector://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")
# test connection
try:
    with engine.connect() as conn:
        print("Connection to database is 👍🏼")
        
    final_data.reset_index(inplace = True)
    final_data.to_sql(name='mpesa_statement', con=engine, if_exists='replace', index=False)
    
except Exception as e:
    print(f"connection Failed {e} 👎🏼")

Connection to database is 👍🏼

Receipt No             object
Completion Time        object
Details                object
Transaction Status     object
Paid in                object
Withdraw\rn            object
Balance                object
Unnamed: 0            float64
dtype: object

# <i>Extrapolatory Data Analysis</i>
* <h3>Finding insight and correlation on dataset</h3>

In [46]:
Column, rows = final_data.shape
print(f"Columns: {Column} Rows: {rows}")

Columns: 274 Rows: 13

In [132]:
final_data.to_excel('mpesa.xlsx')