In [1]:
import pandas as pd
import numpy as np
from dateutil import parser

In [8]:
Data2 = pd.read_excel('/Users/briankimanzi/Documents/programming Languages/PythonProgramming/JupyterNoteBook/Datasets/MPESA_Marylyne.xlsx')

In [15]:
Data2

,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance
0,TD349XUJFS,2025-04-03 18:27:59.962000,Merchant Payment to 168364 - SAWA SHOP 4,Completed,NaN,-65,1260.75
1,TD399XA2KP,2025-04-03 18:26:00.038000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-120,1325.75
2,TD359WGPPX,2025-04-03 18:22:00.019000,Merchant Payment to 679315 - JOANINA KARIMI RU...,Completed,NaN,-70,1445.75
3,TD359Q25IZ,2025-04-03 17:53:00.010000,Pay Bill Charge,Completed,NaN,-57,1515.75
4,TD359Q25IZ,2025-04-03 17:53:00.010000,Pay Bill Online to 400200 - Co- operative Bank...,Completed,NaN,-10500,1572.75
5,TD339NKBL9,2025-04-03 17:41:00.038000,Merchant Payment to 7884584 - IBRAHIM NGUGI 2,Completed,NaN,-160,12072.75
6,TD309I3OBK,2025-04-03 17:12:59.990000,Customer Transfer to - 07******227 ALICE WANJOHI,Completed,NaN,-10,12232.75
7,TD3986S50H,2025-04-03 12:24:59.990000,Merchant Payment to 5461586 - Give and share f...,Completed,NaN,-50,12242.75
8,TD3786IFAF,2025-04-03 12:22:59.981000,Merchant Payment to 6261312 - HANI WARI...,Completed,NaN,-60,12292.75
9,TD286LG960,2025-04-02 23:08:59.971000,Pay Bill Charge,Completed,NaN,-10,12352.75
10,TD286LG960,2025-04-02 23:08:59.971000,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,NaN,-800,12362.75
11,TD2050855M,2025-04-02 18:15:59.990000,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,13162.75
12,TD254ZFVPF,2025-04-02 18:11:59.971000,Customer Payment to Small Business to - 07****...,Completed,NaN,-70,13232.75
13,TD234YSLDD,2025-04-02 18:09:00,Merchant Payment to 7205865 - NAOMI WAMBUI MBU...,Completed,NaN,-45,13302.75
14,TD253LQFA5,2025-04-02 13:21:59.962000,Customer Transfer of Funds Charge,Completed,NaN,-7,13347.75
15,TD253LQFA5,2025-04-02 13:21:59.962000,Customer Transfer to - 2547******523 EMMANUEL ...,Completed,NaN,-150,13354.75
16,TD233JTKAR,2025-04-02 13:09:59.990000,Merchant Payment Online to 7142784 - Naivas Ju...,Completed,NaN,-3006,13504.75
17,TD273G4ON7,2025-04-02 12:47:00.010000,Customer Transfer to - 2547******441 ALFRED JASTO,Completed,NaN,-100,16510.75
18,TD22320TXU,2025-04-02 11:15:00,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,16610.75
19,TD2931QOH3,2025-04-02 11:12:59.990000,Merchant Payment to 7361447 - NOBERT GUCHU NDI...,Completed,NaN,-90,16680.75
20,TD1019N66K,2025-04-01 20:55:00.019000,Pay Bill Charge,Completed,NaN,-5,16770.75
21,TD1019N66K,2025-04-01 20:55:00.019000,Pay Bill to 247247 - Equity Paybill Account Ac...,Completed,NaN,-400,16775.75
22,TD12Z77CC4,2025-04-01 18:20:59.971000,Merchant Payment to 582667 - JACKSON MWAURA MU...,Completed,NaN,-65,17175.75
23,TD19Z68M3F,2025-04-01 18:17:00.038000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-190,17240.75
24,TD15YTLMJ5,2025-04-01 17:14:00.038000,Customer Transfer to - 07******144 JOSEPH GAKOBO,Completed,NaN,-30,17430.75
25,TD10WY4S4I,2025-04-01 10:05:00.010000,Merchant Payment to 5229308 - DUNCAN OINO MASAKI,Completed,NaN,-80,17460.75
26,TD16WXE5RU,2025-04-01 10:00:00.029000,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,17540.75
27,TD14WPCAN2,2025-04-01 09:04:59.981000,Customer Transfer of Funds Charge,Completed,NaN,-7,17610.75
28,TD14WPCAN2,2025-04-01 09:04:59.981000,Customer Transfer to - 07******440 BRANICE Sande,Completed,NaN,-500,17617.75
29,TD10WP20QU,2025-04-01 09:02:00.010000,Customer Transfer of Funds Charge,Completed,NaN,-7,18117.75
30,TD10WP20QU,2025-04-01 09:02:00.010000,Customer Transfer to - 07******261 MACTILDA MA...,Completed,NaN,-500,18124.75
31,TD12WOCO5U,2025-04-01 08:57:00.029000,Airtime Purchase,Completed,NaN,-585,18624.75
32,TCV0VPMLLU,2025-03-31 21:40:00.019000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-890.25,19209.75
33,TCV3VPMAOV,2025-03-31 21:40:00.019000,Receive International Zero Rated Transfer From...,Completed,20100,NaN,20100
34,TCV2UJA0PI,2025-03-31 18:24:59.990000,Merchant Payment Fuliza M-Pesa Online to 78537...,Completed,NaN,-45,0
35,TCV2UJA0PI,2025-03-31 18:24:59.990000,OverDraft of Credit Party,Completed,45,NaN,45
36,TCV9SD9BFX,2025-03-31 10:23:00.010000,Merchant Payment Fuliza M-Pesa Online to 65611...,Completed,NaN,-75,0
37,TCV9SD9BFX,2025-03-31 10:23:00.010000,OverDraft of Credit Party,Completed,75,NaN,75
38,TCU6PYR0H8,2025-03-30 18:00:00,Merchant Payment Fuliza M-Pesa Online to 58266...,Completed,NaN,-65,0
39,TCU6PYR0H8,2025-03-30 18:00:00,OverDraft of Credit Party,Completed,65,NaN,65
40,TCU4PB7P5Q,2025-03-30 15:42:00.029000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-200,0
41,TCU9PB7IKX,2025-03-30 15:42:00.029000,Funds received from - 07******440 BRANICE Sande,Completed,200,NaN,200
42,TCT0JC3QO6,2025-03-29 10:41:59.971000,Merchant Payment Fuliza M-Pesa Online to 78537...,Completed,NaN,-75,0
43,TCT0JC3QO6,2025-03-29 10:41:59.971000,OverDraft of Credit Party,Completed,75,NaN,75
44,TCT5IDX5DN,2025-03-29 01:57:00,Customer Transfer of Funds Charge,Completed,NaN,-7,0
45,TCT5IDX5DN,2025-03-29 01:57:00,Customer Transfer Fuliza MPesa to - 07******98...,Completed,NaN,-500,7
46,TCT5IDX5DN,2025-03-29 01:57:00,OverDraft of Credit Party,Completed,507,NaN,507
47,TCR6DI1IYC,2025-03-27 22:39:59.962000,Funds received from - 07******440 BRANICE Sande,Completed,300,NaN,300
48,TCR0DI1R24,2025-03-27 22:39:59.962000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-300,0
49,TCR5C8A3J3,2025-03-27 18:38:00.010000,Customer Send Money to Micro SME Business wit...,Completed,NaN,-30,0
50,TCR5C8A3J3,2025-03-27 18:38:00.010000,OverDraft of Credit Party,Completed,30,NaN,30
51,TCR6C7PUDE,2025-03-27 18:35:00.038000,Merchant Payment Fuliza M-Pesa Online to 16836...,Completed,NaN,-65,0
52,TCR6C7PUDE,2025-03-27 18:35:00.038000,OverDraft of Credit Party,Completed,65,NaN,65
53,TCR0C560QQ,2025-03-27 18:24:00.029000,Merchant Payment Fuliza M-Pesa Online to 75243...,Completed,NaN,-130,0
54,TCR0C560QQ,2025-03-27 18:24:00.029000,OverDraft of Credit Party,Completed,130,NaN,130
55,TCR8BU34B4,2025-03-27 17:30:59.990000,Funds received from - 07******261 MACTILDA MAT...,Completed,500,NaN,500
56,TCR2BU3BMU,2025-03-27 17:30:59.990000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-500,0
57,TCQ55J91VF,2025-03-26 10:25:00.019000,Merchant Payment Fuliza M-Pesa Online to 78537...,Completed,NaN,-75,0
58,TCQ55J91VF,2025-03-26 10:25:00.019000,OverDraft of Credit Party,Completed,75,NaN,75
59,TCP3375HQ5,2025-03-25 18:31:59.981000,Customer Transfer of Funds Charge,Completed,NaN,-13,0
60,TCP3375HQ5,2025-03-25 18:31:59.981000,Customer Transfer Fuliza MPesa to - 2547******...,Completed,NaN,-900,13
61,TCP3375HQ5,2025-03-25 18:31:59.981000,OverDraft of Credit Party,Completed,801.56,NaN,913
62,TCP834BIU2,2025-03-25 18:18:59.962000,M-Shwari Withdraw,Completed,500,NaN,500
63,TCP434BMQI,2025-03-25 18:18:59.962000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-388.56,111.44
64,TCP82ZQZEQ,2025-03-25 17:57:00.029000,Customer Send Money to Micro SME Business wit...,Completed,NaN,-90,0
65,TCP82ZQZEQ,2025-03-25 17:57:00.029000,OverDraft of Credit Party,Completed,90,NaN,90
66,TCN0TOQF5G,2025-03-23 19:03:59.962000,Merchant Payment Fuliza M-Pesa Online to 54381...,Completed,NaN,-70,0
67,TCN0TOQF5G,2025-03-23 19:03:59.962000,OverDraft of Credit Party,Completed,70,NaN,70
68,TCN0TN0K94,2025-03-23 18:56:00.010000,Customer Transfer Fuliza MPesa to - 2547******...,Completed,NaN,-60,0
69,TCN0TN0K94,2025-03-23 18:56:00.010000,OverDraft of Credit Party,Completed,60,NaN,60
70,TCM2NLMV3M,2025-03-22 12:27:59.962000,Merchant Payment Fuliza M-Pesa Online to 68325...,Completed,NaN,-70,0
71,TCM2NLMV3M,2025-03-22 12:27:59.962000,OverDraft of Credit Party,Completed,70,NaN,70
72,TCM1NKODHT,2025-03-22 12:20:59.971000,Customer Transfer Fuliza MPesa to - 2547******...,Completed,NaN,-60,0
73,TCM1NKODHT,2025-03-22 12:20:59.971000,OverDraft of Credit Party,Completed,60,NaN,60
74,TCL5KHWTMZ,2025-03-21 17:50:00.038000,Merchant Payment Fuliza M-Pesa Online to 58266...,Completed,NaN,-65,0
75,TCL5KHWTMZ,2025-03-21 17:50:00.038000,OverDraft of Credit Party,Completed,34.71,NaN,65
76,TCL5IQ55O7,2025-03-21 10:48:00,Withdrawal Charge,Completed,NaN,-11,30.29
77,TCL5IQ55O7,2025-03-21 10:48:00,Customer Withdrawal At Agent Till 453478 - Mar...,Completed,NaN,-100,41.29
78,TCK0GB0YHW,2025-03-20 18:36:00,Customer Payment to Small Business to - 07****...,Completed,NaN,-40,141.29
79,TCK1G1NU6Z,2025-03-20 17:51:00,Customer Payment to Small Business to - 2547**...,Completed,NaN,-25,181.29
80,TCK3FSFRC1,2025-03-20 16:59:59.971000,Customer Payment to Small Business to - 07****...,Completed,NaN,-40,206.29
81,TCK0EBUZ0U,2025-03-20 10:54:00.029000,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-75,246.29
82,TCJ3C8U6TX,2025-03-19 19:21:59.962000,Merchant Payment to 168364 - SAWA SHOP 4,Completed,NaN,-65,321.29
83,TCJ5C7JGWT,2025-03-19 19:16:59.981000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-190,386.29
84,TCJ29ZHTZ2,2025-03-19 10:59:00.010000,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-75,576.29
85,TCI87FVEPQ,2025-03-18 18:11:59.971000,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-45,651.29
86,TCI97EBYGR,2025-03-18 18:04:59.981000,Merchant Payment to 582667 - JACKSON MWAURA MU...,Completed,NaN,-65,696.29
87,TCI77DID9H,2025-03-18 18:00:00,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-70,761.29
88,TCI45X043O,2025-03-18 12:17:00.038000,Customer Transfer to - 07******227 ALICE WANJOHI,Completed,NaN,-30,831.29
89,TCI95I61L3,2025-03-18 10:30:00,Merchant Payment to 6561198 - MERCYLINE MUTHON...,Completed,NaN,-30,861.29
90,TCH42W63BU,2025-03-17 17:46:00.019000,Customer Payment to Small Business to - 01****...,Completed,NaN,-100,891.29
91,TCH01B02PQ,2025-03-17 11:26:00.010000,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,991.29
92,TCH71AVMHV,2025-03-17 11:24:59.962000,Deposit of Funds at Agent Till 453478 - Maryju...,Completed,1000,NaN,1061.29
93,TCH7185869,2025-03-17 11:06:00,Merchant Payment to 244268 - Cell express ltd,Completed,NaN,-75,61.29
94,TCG7XQKYYF,2025-03-16 18:24:59.990000,Merchant Payment to 168364 - SAWA SHOP 4,Completed,NaN,-65,136.29
95,TCG3XPTR45,2025-03-16 18:20:59.971000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-190,201.29
96,TCG1XNWAPD,2025-03-16 18:09:59.962000,Customer Transfer to - 07******397 PETERSON NJIRU,Completed,NaN,-100,391.29
97,TCG3XKLOMN,2025-03-16 17:51:00,Pay Bill Charge,Completed,NaN,-5,491.29
98,TCG3XKLOMN,2025-03-16 17:51:00,Pay Bill to 247247 - Equity Paybill Account Ac...,Completed,NaN,-350,496.29
99,TCG1WR4MAV,2025-03-16 14:46:59.981000,Merchant Payment to 7078398 - Swaggy milkyway,Completed,NaN,-50,846.29
100,TCG7WPX1JH,2025-03-16 00:00:00,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-103.71,896.29
101,TCG4WPX568,2025-03-16 00:00:00,M-Shwari Withdraw,Completed,1000,NaN,1000
102,TCG5WICI2N,2025-03-16 00:00:00,Customer Bundle Purchase with Fuliza to 409344...,Completed,NaN,-141,0
103,TCG5WICI2N,2025-03-16 00:00:00,OverDraft of Credit Party,Completed,102.68,NaN,141
104,TCG6VQBK1C,2025-03-16 00:00:00,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-45,38.32
105,TCG7VPY6QZ,2025-03-16 00:00:00,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,83.32
106,TCF7TBJED1,2025-03-15 00:00:00,Customer Payment to Small Business to - 07****...,Completed,NaN,-65,153.32
107,TCF6TA6QCI,2025-03-15 00:00:00,Merchant Payment to 9743080 - PAUL MUTAI KAMAU,Completed,NaN,-65,218.32
108,TCF4T8KZUW,2025-03-15 00:00:00,Merchant Payment to 7524380 - JUDITH KATHURE M...,Completed,NaN,-150,283.32
109,TCF6S0ZSCS,2025-03-15 00:00:00,Customer Transfer of Funds Charge,Completed,NaN,-7,433.32
110,TCF6S0ZSCS,2025-03-15 00:00:00,Customer Payment to Small Business to - 2547**...,Completed,NaN,-250,440.32
111,TCF5RZU9X1,2025-03-15 00:00:00,Customer Transfer to - 2547******423 FRANCIS K...,Completed,NaN,-50,690.32
112,TCF3RYWSH5,2025-03-15 00:00:00,Merchant Payment to 5408820 - SHEM JARED MACHONI,Completed,NaN,-200,740.32
113,TCF4RXKCGQ,2025-03-15 00:00:00,Merchant Payment to 7119402 - BILLION JAMBO TR...,Completed,NaN,-1530,940.32
114,TCF9RUULWT,2025-03-15 00:00:00,Customer Transfer to - 2547******651 EVANS OMU...,Completed,NaN,-50,2470.32
115,TCF6RJ9Y3Y,2025-03-15 00:00:00,Merchant Payment to 7884584 - IBRAHIM NGUGI 2,Completed,NaN,-160,2520.32
116,TCF8RIXCNA,2025-03-15 00:00:00,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-45,2680.32
117,TCF7RHN3OX,2025-03-15 00:00:00,Customer Payment to Small Business to - 07****...,Completed,NaN,-75,2725.32
118,TCE0OVSHDC,2025-03-14 00:00:00,Receive International Transfer From 339888 - C...,Completed,1050,NaN,2800.32
119,TCE3OLH0B5,2025-03-14 00:00:00,Merchant Payment to 582667 - JACKSON MWAURA MU...,Completed,NaN,-65,1750.32
120,TCE0OKINK0,2025-03-14 00:00:00,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-190,1815.32
121,TCE1MIYPTD,2025-03-14 00:00:00,Merchant Payment to 6561198 - MERCYLINE MUTHON...,Completed,NaN,-45,2005.32
122,TCD3J66L6P,2025-03-13 00:00:00,Customer Transfer to - 07******227 ALICE WANJOHI,Completed,NaN,-10,2050.32
123,TCD1J44RIT,2025-03-13 00:00:00,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-28,2060.32
124,TCD6I8EC7W,2025-03-13 00:00:00,Customer Payment to Small Business to - 07****...,Completed,NaN,-70,2088.32
125,TCD0I5S7HU,2025-03-13 00:00:00,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-28,2158.32
126,TCC9FOHFI5,2025-03-12 00:00:00,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-8,2186.32
127,TCC1FFRKCH,2025-03-12 00:00:00,Customer Transfer of Funds Charge,Completed,NaN,-7,2194.32
128,TCC1FFRKCH,2025-03-12 00:00:00,Customer Payment to Small Business to - 2547**...,Completed,NaN,-145,2201.32
129,TCC9FEE5GF,2025-03-12 00:00:00,Pay Bill Charge,Completed,NaN,-5,2346.32
130,TCC9FEE5GF,2025-03-12 00:00:00,Pay Bill to 522533 - Lipa na KCB Acc. 7958408,Completed,NaN,-150,2351.32
131,TCC6ES9IZM,2025-03-12 00:00:00,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-10,2501.32
132,TCC0DJVIRM,2025-03-12 00:00:00,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-28,2511.32
133,TCC9DIRYUH,2025-03-12 10:32:00.010000,Merchant Payment to 7853780 - MICHAEL KABIRU K...,Completed,NaN,-75,2539.32
134,TCC9DHOJ9H,2025-03-12 10:23:59.971000,Merchant Payment to 5231024 - DUNCAN OINO MASA...,Completed,NaN,-80,2614.32
135,TCB2B2S3HG,2025-03-11 18:36:59.962000,Merchant Payment to 9743080 - PAUL MUTAI KAMAU,Completed,NaN,-65,2694.32
136,TCB3B255EB,2025-03-11 18:33:59.990000,Merchant Payment to 7524380 - JUDITH KATHURE M...,Completed,NaN,-10,2759.32
137,TCB7B1WVHP,2025-03-11 18:33:00.029000,Merchant Payment to 7524380 - JUDITH KATHURE M...,Completed,NaN,-150,2769.32
138,TCB5AXMOBF,2025-03-11 18:13:59.981000,Funds received from - 2547******825 hellen muntet,Completed,2500,NaN,2919.32
139,TCB5AT8DJV,2025-03-11 17:53:00.010000,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-48,419.32
140,TCB88UWCME,2025-03-11 10:16:59.981000,Merchant Payment to 6561198 - MERCYLINE MUTHON...,Completed,NaN,-75,467.32
141,TCB98U8PE9,2025-03-11 10:12:00,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,542.32
142,TCA36T1NSL,2025-03-10 19:12:00,Recharge for Customer to 4093441SAFARICOM DATA...,Completed,NaN,-20,612.32
143,TCA96IABQD,2025-03-10 18:26:00.038000,Merchant Payment to 168364 - SAWA SHOP 4,Completed,NaN,-65,632.32
144,TCA66H9O0A,2025-03-10 18:20:59.971000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-190,697.32
145,TCA9526349,2025-03-10 13:11:00.038000,Recharge for Customer to 4093441SAFARICOM DATA...,Completed,NaN,-20,887.32
146,TCA64VCHFM,2025-03-10 12:24:59.990000,Customer Bundle Purchase to 4093441SAFARICOM D...,Completed,NaN,-20,907.32
147,TCA24GX4IC,2025-03-10 10:45:00.029000,Recharge for Customer to 4093441SAFARICOM DATA...,Completed,NaN,-40,927.32
148,TCA04BWAUS,2025-03-10 10:11:00.038000,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,967.32
149,TCA84B12X2,2025-03-10 10:05:00.010000,M-Shwari Withdraw,Completed,1000,NaN,1037.32
150,TC97286K9R,2025-03-09 18:42:00.029000,Airtime Purchase,Completed,NaN,-129,37.32
151,TC9727AJEP,2025-03-09 18:38:00.010000,Customer Transfer to - 2547******259 DENNIS MU...,Completed,NaN,-60,166.32
152,TC88USVZDG,2025-03-08 11:55:00.019000,Funds received from - 2547******651 DICKSON OM...,Completed,30,NaN,226.32
153,TC61MN3UXF,2025-03-06 16:57:00,Withdrawal Charge,Completed,NaN,-52,196.32
154,TC61MN3UXF,2025-03-06 16:57:00,Customer Withdrawal At Agent Till 2880226 - PO...,Completed,NaN,-3200,248.32
155,TC67MMTRRF,2025-03-06 16:54:59.990000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-51.68,3448.32
156,TC69MMU3LB,2025-03-06 16:54:59.990000,M-Shwari Withdraw,Completed,3500,NaN,3500
157,TC58IJ38N2,2025-03-05 18:51:00.029000,Send Money Reversal via API to - 2541******288...,Completed,NaN,-30,0
158,TC57IJ3HN7,2025-03-05 18:49:00.019000,NaN,Completed,30,NaN,30
159,TC56IIFGT0,2025-03-05 18:45:59.962000,Funds received from - 01******288 JOYCE YVONNE,Completed,30,NaN,30
160,TC52IIFKM4,2025-03-05 18:45:59.962000,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,NaN,-30,0
161,TC50I3SW9U,2025-03-05 17:35:00.010000,Customer Send Money to Micro SME Business wit...,Completed,NaN,-40,0
162,TC50I3SW9U,2025-03-05 17:35:00.010000,OverDraft of Credit Party,Completed,40,NaN,40
163,TC51HT8697,2025-03-05 16:34:00.019000,Customer Transfer Fuliza MPesa to - 07******22...,Completed,NaN,-20,0
164,TC51HT8697,2025-03-05 16:34:00.019000,OverDraft of Credit Party,Completed,11.16,NaN,20
165,TC54GAP1MU,2025-03-05 10:32:59.971000,Merchant Payment to 543817 - Benjac food produ...,Completed,NaN,-70,8.84
166,TC56GAF3MA,2025-03-05 10:30:59.962000,Merchant Payment to 244268 - Cell express ltd,Completed,NaN,-75,78.84
167,TC46DNTQ82,2025-03-04 18:29:00.010000,Customer Payment to Small Business to - 07****...,Completed,NaN,-70,153.84
168,TC42DMSTC8,2025-03-04 18:24:00.029000,Merchant Payment to 9472378 - Mohamed Dulacha Ali,Completed,NaN,-100,223.84
169,TC46CC1NLW,2025-03-04 13:45:00.029000,Customer Payment to Small Business to - 07****...,Completed,NaN,-50,323.84
170,TC43CBHCE7,2025-03-04 13:41:00.010000,Merchant Payment to 114121 - WILSON KINYANJUI ...,Completed,NaN,-65,373.84
171,TC47CB589R,2025-03-04 13:39:00,Merchant Payment to 679315 - JOANINA KARIMI RU...,Completed,NaN,-20,438.84
172,TC47CAKRAD,2025-03-04 13:36:00.029000,Customer Transfer to - 2547******867 MARCOS OT...,Completed,NaN,-100,458.84
173,TC33999M9F,2025-03-03 19:25:00.019000,Pay Bill Charge,Completed,NaN,-5,558.84
174,TC33999M9F,2025-03-03 19:25:00.019000,Pay Bill to 247247 - Equity Paybill Account Ac...,Completed,NaN,-345,563.84
175,TC308X31OQ,2025-03-03 18:35:00.038000,M-Shwari Deposit,Completed,NaN,-6000,908.84
176,TC328WN91Y,2025-03-03 18:33:00.029000,Merchant Payment to 7524380 - JUDITH KATHURE M...,Completed,NaN,-150,6908.84
177,TC318VMOJH,2025-03-03 18:29:00.010000,Pay Bill to 247247 - Equity Paybill Account A...,Completed,NaN,-80,7058.84
178,TC308UINLU,2025-03-03 18:24:00.029000,Withdrawal Charge,Completed,NaN,-309,7138.84
179,TC308UINLU,2025-03-03 18:24:00.029000,Customer Withdrawal At Agent Till 087443 - Dot...,Completed,NaN,-56000,7447.84
180,TC347FGG6Y,2025-03-03 13:25:59.981000,Pay Bill Charge,Completed,NaN,-57,63447.84
181,TC347FGG6Y,2025-03-03 13:25:59.981000,Pay Bill Online to 400200 - Co- operative Bank...,Completed,NaN,-10500,63504.84
182,TC367FBGYI,2025-03-03 13:25:00.019000,Pay Bill Charge,Completed,NaN,-10,74004.84
183,TC367FBGYI,2025-03-03 13:25:00.019000,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,NaN,-800,74014.84
184,TC3478N35S,2025-03-03 12:44:00.038000,Customer Transfer of Funds Charge,Completed,NaN,-7,74814.84
185,TC3478N35S,2025-03-03 12:44:00.038000,Customer Transfer to - 2547******866 FRANCIS M...,Completed,NaN,-150,74821.84

In [38]:
# Anonymising the dataset 
def transaction(x):
    x = str(x).strip()
    if x.startswith('Merchant Payment'):
        index = x.find(' - ')+2
        name = x[index:].strip().upper()
        
        return 'BUY GOODS', name

    elif x.startswith('Deposit of Funds'):
        index = x.find(' - ')+2
        name = x[index:].strip().upper()
        
        return 'AGENT DEPOSIT', name

    elif x.startswith('OD Loan Repayment'):
        return 'FULIZA REPAYMENT', 'FULIZA'

    elif x.startswith('OverDraft of Credit Party'):
        return 'FULIZA TAKEN', 'FULUZA'

    elif x.startswith('M-Shwari Deposit'):
        return 'M-SHWARI DEPOSIT FROM M-PESA', 'M-SHWARI'
        
    elif x.startswith('KCB M-PESA Deposit'):
        return 'KCB M-PESA DEPOSIT FROM M-PESA', 'KCB DEPOSIT'

    elif x.startswith('KCB M-PESA Withdraw'):
        return 'KCB M-PESA WITHDRAW FROM M-PESA', 'KCB WITHDRAW'

    elif x.startswith('Customer Transfer'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
                
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        return 'SEND MONEY', name

    elif x.startswith('M-Shwari Withdraw'):
        
        return 'M-SHWARI WITHDRAW FROM M-PESA', 'M-SHWARI WITHDRAW'

    elif x.startswith('Pay Bill Charge'):
        # if x.strip() == 'Pay Bill Charge':
            return 'PAY BILL CHARGES', 'TRANSACTION COST'
        
    elif x.startswith('Pay Bill Online to'):
        if x == 'Pay Bill Online to':  
            return 'PAY BILL ONLINE', 'TRANSACTION COST'
        else:
            start = len('Pay Bill Online to')+9
            end = x.lower().find('acc')
            name = x[start:end].strip().upper()
            return 'PAY BILL', name
    elif x.startswith('Pay Bill'):
        if x == 'Pay Bill':  
            return 'PAY BILL', 'UNKNOWN'
        else:
            start = x.find(' - ') + 3 if ' - ' in x else len('Pay Bill') + 1
            end = x.lower().find('acc')
            name = x[start:end].strip().upper() if end != -1 else x[start:].strip().upper()
            return 'PAY BILL', name

    elif x.startswith('Funds received'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        
        return 'RECEIVED FUNDS', name

    elif x.startswith('Customer Payment to Small Business') or x.startswith('Customer Send Money'):
        index = x.find(' - ')
        to_search = x[index:]
        last = 1

        for i in range(len(to_search)):
            try:
                int(to_search[i])
                last = i
            except:
                v = 10

        name = x[index+last+2:].strip().upper()
        
        return 'POCHI LA BIASHARA', name

    elif x.startswith('Airtime Purchase'):
        return 'AIRTIME PURCHASE', 'AIRTIME'

    elif x.startswith('Business Payment From'):
        index = x.find(' - ')
        end = x.lower().find('via')
        to_search = x[index:]
        last = 1
        name = x[index:end].strip().upper()
        return 'FUNDS RECEIVED FROM BUSINESS', name

    elif x.startswith('Customer Transfer of Funds Charge'):
        return 'TRANSACTION COST', 'TRANSACTION COST'
    
    elif x.startswith('Buy Bundles Online'):
        return 'BUNDLES PURCHASE', 'BUNDES PURCHASE'
    
    elif x.startswith('Customer Withdrawal'):
        index = x.find(' - ')+2
        name = x[index:].strip().upper()
        return 'CASH WITHDRAWAL', name
    
    elif x.startswith('Withdrawal Charge'):
        return 'CASH WITHDRAWAL CHARGES', "TRANSACTION COST"

    elif x.startswith('Customer Bundle Purchase') or x.startswith('Recharge for Customer'):
        return 'CUSTOMER BUNDLE PURCHASE', 'SAFARICOM DATA BUNDLES'

    elif x.startswith('Promotion Payment'):
        return 'PROMOTION PAYMENT', 'M-PESA OFFERS. VIA API'
    
    elif x.startswith('Business Payment'):
        return 'BUSINESS PAYMENT', 'CO-OP BANK VIA API'
        
    elif x.startswith('Receive International'):
        index = x.find(' - ')+3
        remaining_str = x[index:]
        name = remaining_str.split('.')[0].strip().upper()
        return 'RECEIVE INTERNATION TRANSFER', name
        
    elif x.startswith('Savings Contribution'):
        return 'TO HUSTLER FUND SAVINGS', 'HUSTLER FUND'
    
    elif x.startswith('Term Loan Disbursement for H- Fund') or x.startswith('Term Loan Disbursement for H-Fund'):
        return 'HUSTLER FUND Disbursement'.upper(), 'HUSTLER FUND'
    
    elif x.startswith('Term Loan Repayment for H- Fund') or x.startswith('Term Loan Repayment for H-Fund'):
        return 'HUSTLER FUND REPAYMENT', 'HUSTLER FUND'
    
    else:
        return 'UNIDENTIFIED', 'UNIDENTIFIED'

In [ ]:
Data2['Details'] = Data2['Details'].apply(lambda x: x.replace('\r', ' '))

In [39]:
details = list(Data2['Details'].apply(lambda x: transaction(x)).values)
transactionType = [i[0] for i in details]
TransactionParty = [i[1] for i in details]

Empty DataFrame
Columns: [Receipt No., Completion Time, Details, Transaction Status, Paid In, Withdrawn, Balance]
Index: []